import {setImage, changeId}  from './setImage.js'
import { openMainModal, closeMainModal } from './mainModal.js'
import { addItem, rmvItem } from './quantity.js'
import { openCartModal } from './cartModal.js'
import * as quantity from './quantity.js'
